FROM python:3.9
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD . /code/

# Run start.sh (CMD is overriden if run via docker-compose.yml)
RUN chmod +x start.sh
CMD ./start.sh