FROM python:3.9
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD . /code/

# Run django server (CMD is overriden if run via docker-compose.yml)
CMD python manage.py runserver 0.0.0.0:$PORT --settings=config.settings.prod