FROM python:3.9

# Install and copy the necessary files to use Heroku Exec (SSH Tunneling) with Docker
# Ref: https://devcenter.heroku.com/articles/exec#using-with-docker
RUN apt-get -y update
RUN apt-get install -y iproute2 --no-install-recommends
ADD ./.profile.d /app/.profile.d
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
ADD . /code/

# Run start.sh (CMD is overriden if run via docker-compose.yml)
RUN chmod +x start.sh
CMD ./start.sh